website/posts/routes.py
from flask import Blueprint, request, redirect, url_for, render_template, abort
from flask_login import login_required, current_user
from datetime import datetime
from uuid import uuid4
from website.database.db import get_blog_collection

posts = Blueprint('posts', __name__)

@posts.route("/post/<post_id>", methods=["GET"])
def post(post_id):
    coll = get_blog_collection()
    return render_template('post.html', post=coll.find_one({"blog_id": post_id}))

@login_required
@posts.route("/add_post", methods=["POST", "GET"])
def add_post():
    if request.method == "POST":
        author = request.form["author"]
        title = request.form["title"]
        content = request.form["content"]
        id = uuid4()
        
        post = {'blog_id': str(id),
                'author': author,
                'title': title, 
                'content': content,
                'date_posted': datetime.now().strftime("%m-%d-%Y %I:%M%p")
                }
        
        coll = get_blog_collection()

        coll.insert_one(post)

        return redirect(url_for("main.index"))

    elif request.method == "GET":

        return render_template("add_post.html")
    
@login_required
@posts.route("/post/<post_id>/delete_post", methods=["POST"])
def delete_post(post_id):
    if request.method == "POST":
        # look for post via blog id and delete only one
        get_blog_collection().find_one_and_delete({"blog_id": post_id})

        return redirect(url_for("main.index"))

@login_required
@posts.route("/post/<post_id>/update_post", methods=["POST", "GET"])
def update_post(post_id):
    coll = get_blog_collection()
    if request.method == "POST":
        # update data
        upd_title = request.form["title"]
        upd_content = request.form["content"]
        coll.update_one({"blog_id": post_id}, 
                        {"$set": {"title": upd_title,
                                "content": upd_content}}
                            )
        
        # if post.modified_count == 0:
        #     return abort(500)
        # else:

        return redirect(url_for("main.index"))
    
    elif request.method == "GET":
        post = coll.find_one({"blog_id": post_id}) #returns dict
        title = post.get("title")
        content = post.get("content")

        return render_template("update_post.html", post_id=post_id, title=title, content=content)

website/users/routes.py
from flask import (Blueprint, request, redirect, url_for, render_template,
                   flash)
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import check_password_hash, generate_password_hash
from website.database.db import get_users_collection
from website.models.user import User

users = Blueprint('users', __name__)

# TODO: Add better error handling

@users.route("/login", methods=["POST", "GET"])
def login():
    if request.method == "POST":
        try:
            email = request.form["email"]
            password = request.form["password"]
            remember = False # used for "remember me" chckbox
            if request.form["password"]:
                remember = True

        except Exception as e:
            print(f"Error: {e}")

        users = get_users_collection()

        doc = users.find_one({"email": email})

        if doc and check_password_hash(doc["password"], password): # user found

            if check_password_hash(doc["password"], password):
                user = User(doc)
                login_user(user, remember=remember) # true or false
                flash(f"User {user.username} Found. Logging in now!", category="success")
                return redirect(url_for("main.index"))
            
            else: #wrong password
                flash("Wrong password!", category="error")
                return redirect(url_for("users.login"))

        else:
            flash("User not found!", category="error")
            return redirect(url_for("users.login"))
        
    else:
        return render_template("login.html")

@login_required
@users.route("/logout")
def logout():
    logout_user()
    flash("Successfully logged out!", category="success")
    return redirect(url_for("main.index"))
    
@users.route("/register", methods=["POST", "GET"])
def register():
    if request.method == "POST":
        username = request.form["username"]
        email = request.form["email"]
        hashed_password = generate_password_hash(request.form["password"], method="scrypt", salt_length=16)
        user_coll = get_users_collection() 

        #TODO: validate email and password via regex

        user = {
            "username": username, 
            "email": email, 
            "password": hashed_password,
            "role": "user"
        }

        # check if user exists via email or username and stop duplicates
        doc = user_coll.find_one({
            "$or": [
                {"email": email}, 
                {"username": username}
                ]
            })

        if doc:
            if doc["username"] == username:
                flash("Username already taken!", category="error")
        
            else:
                flash("Email already exists, login instead", category="error")
                
            return redirect(url_for("users.login"))
        
        else:
        # success case 
            try:
                user_coll.insert_one(user) # adds user to db
                doc = user_coll.find_one({"email": email}) # finds recently made user to make into User obj
                flash(message=f"User {username} created!", category="success")
                user = User(doc) 
                login_user(user, remember=True)
                return redirect(url_for("main.index"))
            
            except Exception as e:
                return f"ERROR:{e}"
        
    else:
        return render_template("register.html")

website/templates/about.html
{% extends "base.html"%}

{% block head %}
{{super()}}

{% endblock %}

{% block content %}

<div class="about_me ">
    
    <img src="static/img/asukapfp.jpg" alt="" width="200" class="about_me_img">
    <h3>My time: <strong>{{cur_time}}</strong></h3>
    <p>My name is Yahir and I'm a 22 year old Computer Science and Cognitive Studies student.
       Some stuff I am interested in include anything about philosophy, psychology, 
       neuroscience, and computers. 
    </p>
    <p><strong>What made you major in CS and Cog?</strong></p>
    <p>The main reason that I majored in CS and then Cog was due to the fact that my 
        university does not have a neuroscience major. So I just chose the next sciency thing that seemed 
        interesting. Even though I am in CS, Neuroscience is the field I have been wanting to 
        get into since I was 16. Now 6 years later, I am still not officially studying neuroscience but 
        I'm still not giving up. After I graduate, I will see what options I have to continue my education 
        in either CS or neuroscience or maybe both.
    </p>
    <p><strong>What are you currently studying?</strong></p>
    <p>I am currently studying for Comptia A+ and web development with Python.
        I plan on studying for at least the Network+, Security+, CySa+, and Linux+
        throughout the next 6 - 12 months. I do want to make the move towards cybersecurity 
        since that seems a lot more fun to do for a job than programming. I do enjoy programming
        but mainly for myself so I will just continue to learn things I want to rather than following 
        some roadmap to get a job. I am also going into my last semester of college. 
    </p>
    <p><strong>What are your long term goals?</strong></p>
    <p></p>
</div>


{% endblock %}

website/templates/add_blog.html
{% extends "base.html" %}

{% block content %}
<form method="POST" action=" {{url_for('posts.add_blog')}} ">
    <div class="form-group">
        <label for="author">Author: </label>
        <input type="text" class="form-control" id="author" name="author" value="Yahir Orozco">
    </div>
    <div class="form-group">
        <label for="title">Title: </label>
        <input type="text" class="form-control" id="title" name="title">
    </div>
    <div class="form-group">
        <label for="content">Content: </label>
        <textarea rows="4" cols="50" id="content" class="form-control" name="content"></textarea>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Submit</button> 
    </div>
       
</form>
{% endblock%}

website/templates/add_post.html
{% extends "base.html" %}

{% block content %}
<form method="POST" action=" {{url_for('posts.add_post')}} ">
    <div class="form-group">
        <label for="author">Author: </label>
        <input type="text" class="form-control" id="author" name="author" value="Yahir Orozco">
    </div>
    <div class="form-group">
        <label for="title">Title: </label>
        <input type="text" class="form-control" id="title" name="title">
    </div>
    <div class="form-group">
        <label for="content">Content: </label>
        <textarea rows="4" cols="50" id="content" class="form-control" name="content"></textarea>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Submit</button> 
    </div>
       
</form>
{% endblock%}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Yblog{% endblock %}</title>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/about.css')}}">
</head>

<body>
    {% block navbar %}
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Yblog</a>
                </div>

                <div class="collapse navbar-collapse" id="navbar">
                    <div class="nav navbar-nav navbar-left">
                        <ul class="nav navbar-nav">
                            <li><a href="/home">Home</a></li>
                            <li><a href="/about">About</a></li>
                            <li><a href="https://github.com/yorozc" target="_blank">Github</a></li>
                        </ul>
                    </div>
                    
                    {% if current_user.is_authenticated %}
                        <div class="nav navbar-nav navbar-right">
                            <!--Checks for admin-->
                            {% if current_user.is_admin %}
                            <ul class="nav navbar-nav">
                                <li><a href="/add_post">Create</a></li>
                                <li><a href="#">Settings</a></li>
                                <li><a href="/logout">Logout</a></li>
                            </ul>
                            {% else %}
                            <ul class="nav navbar-nav">
                                <li><a href="#">Settings</a></li>
                                <li><a href="/logout">Logout</a></li>
                            </ul>
                            {% endif %}
                        </div>
                    {% else %}
                        <div class="nav navbar-nav navbar-right">
                        <ul class="nav navbar-nav">
                            <li><a href="/login">Login</a></li>
                            <li><a href="/register">Register</a></li>
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == "success" %}
                        <div class="flash_message success">
                            {{ message }}
                        </div>
                    {% else %}
                        <div class="flash_message error">
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
    {% endblock %}

    

    <main role="main" class="container">
    <div class="row">
        <div class="col-md-8 container">
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
                </p>
            </div>
        </div>
    </div>
    </main>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    {% block scripts %}
    {{moment.include_moment()}}
    {% endblock %}
</body>
</html>

website/templates/blog.html
{% extends "base.html" %}

{% block title %}Yblog{% endblock %}

{% block content %}
 
<div class="blog-container">
    <div class="blog-meta-data text-muted">
        <p class="author"> {{ post.author }}</p>
        <p class="date_posted"> {{ post.date_posted }}</p>
        <form action="{{ url_for('posts.delete_blog', blog_id=post.blog_id) }}" method="POST">
            <button type="submit" class="del-btn">Delete</button> 
        </form>
    </div>
    <div class="article-content">
        <h1 class="blog-title">{{ post.title }}</h1>
        <p class="blog-content">{{ post.content }}</p>
    </div>
</div>

{% endblock content%}

website/templates/index.html
{% extends "base.html" %}

{% block title %}Yblog{% endblock %}

{% block content %}

    {% for post in posts | reverse %}
    
    <div class="blog-container">
        <div class="blog-meta-data text-muted">
            <p class="author"> {{ post.author }}</p>
            <p class="date_posted"> {{ post.date_posted }}</p>
            {% if current_user.is_admin %}
                <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('posts.update_post', post_id=post.blog_id) }}">Update</a>
                <form action="{{ url_for('posts.delete_post', post_id=post.blog_id) }}" method="POST">
                    <button type="submit" class="del-btn">Delete</button> 
                </form>
            {% endif %}
        </div>
        <div class="article-content">
            <h1 class="blog-title"><a href="{{ url_for ('posts.post', post_id=post.blog_id) }}">{{ post.title }}</a></h1>
            <p class="blog-content">{{ post.content }}</p>
        </div>
    </div>
    
    {% endfor %}
{% endblock content%}

website/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="POST" action=" {{url_for('users.login')}} ">
    <div class="form-group">
        <label for="email">Email: </label>
        <input type="email" class="form-control" id="email" name="email">
    </div>
    <div class="form-group">
        <label for="password">Password: </label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <div class="form-group">
        <input type="checkbox" id="remember" name="remember">
        <label for="remember">Remember Me</label> 
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Submit</button> 
    </div>
</form>

{% endblock %}

website/templates/post.html
{% extends "base.html" %}

{% block title %}Yblog{% endblock %}

{% block content %}
 
<div class="blog-container">
    <div class="blog-meta-data text-muted">
        <p class="author"> {{ post.author }}</p>
        <p class="date_posted"> {{ post.date_posted }}</p>
        {% if current_user.is_admin %}
            <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('posts.update_post', post_id=post.blog_id) }}">Update</a>
            <form action="{{ url_for('posts.delete_post', post_id=post.blog_id) }}" method="POST">
                <button type="submit" class="del-btn">Delete</button> 
            </form>
        {% endif %}
    </div>
    <div class="article-content">
        <h1 class="blog-title">{{ post.title }}</h1>
        <p class="blog-content">{{ post.content }}</p>
    </div>
</div>

{% endblock content%}

website/templates/register.html
{% extends "base.html" %}

{% block content %}
<form method="POST" action=" {{url_for('users.register')}} ">
    <div class="form-group">
        <label for="username">Username: </label>
        <input type="username" class="form-control" id="username" name="username">
    </div>
    <div class="form-group">
        <label for="email">Email: </label>
        <input type="email" class="form-control" id="email" name="email">
    </div>
    <div class="form-group">
        <label for="password">Password: </label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Submit</button> 
    </div>
       
</form>
{% endblock %}

website/templates/update_post.html
{% extends "base.html" %}

{% block content %}
<form method="POST" action=" {{url_for('posts.update_post', post_id=post_id)}} ">
    <div class="form-group">
        <label for="title">Title: </label>
        <input type="text" class="form-control" id="title" name="title" value="{{title}}">
    </div>
    <div class="form-group">
        <label for="content">Content: </label>
        <textarea rows="4" cols="50" id="content" class="form-control" name="content">{{content}}</textarea>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Submit</button> 
    </div>
       
</form>
{% endblock%}